name: testing code transfer
#
on:
  push:
    branches: [main]
permissions:
  id-token: write
  contents: write
  repository-projects: write
  pull-requests: write
  deployments: write
jobs:
  checkBuild:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Push directory to another repository
      uses: cpina/github-action-push-to-another-repository@v1.5.1
   
   
