
name: testing code transfer
#
on:
  push:
    branches: [main]
permissions:
  id-token: write
  contents: write
  repository-projects: write
  pull-requests: write
  deployments: write
jobs:
  checkBuild:
    name: build
    runs-on: [self-hosted]
    steps:
    
    - name: checkout
      uses: actions/checkout@v2

    - name: remove current remote repo
      run: rm -rf .git      
    - name: Preparing worktree
      working-directory: .
      run: |
          git clone https://.:${{ secrets.GH_PAT }}@github.com/akash97716/test-from-local sm
          #rm everything but the .git directory
          cp -R test-from-local sm/
          #copy source\files target
          cd sm
          git add .
          git diff-index --quiet HEAD || git commit -m "tesing copy"
          git push https://github.com/akash97715/sm.git master
